---
- name: deploy prometheus server
  hosts: promserver
  vars: 
    prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v2.10.0/prometheus-2.10.0.linux-amd64.tar.gz"    
  roles:
    - promserver
