---
- name: deploy prometheus server
  hosts: promserver
  vars:
    promversion: "prometheus-2.10.0.linux-amd64"
    prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v2.10.0/{{ promversion }}.tar.gz"    
  roles:
    - promserver
